

export function getAllHeroes(){
 return [
    {
      name: 'spiderman',
      ability: 'attacker',
      id: 0,
      firstTrainedDay: 0,
      SuitColors: 'red',
      StartingPower: 25,
      CurrentPower: 25,
      lastTimeTrained: undefined,
      HerosTrainingTimes: 0,
    },
    {
      name: 'ironMan',
      ability: 'attacker',
      id: 0,
      firstTrainedDay: 0,
      SuitColors: 'red and gold',
      StartingPower: 30,
      CurrentPower: 30,
      lastTimeTrained: undefined,
      HerosTrainingTimes: 0,
    },
    {
      name: 'batman',
      ability: 'attacker',
      id: 0,
      firstTrainedDay: 0,
      SuitColors: 'black',
      StartingPower: 25,
      CurrentPower: 25,
      lastTimeTrained: undefined,
      HerosTrainingTimes: 0,
    },
    {
      name: 'captain_America',
      ability: 'defender',
      id: 0,
      firstTrainedDay: 0,
      SuitColors: 'red',
      StartingPower: 14,
      CurrentPower: 14,
      lastTimeTrained: undefined,
      HerosTrainingTimes: 0,
    },
    {
      name: 'dark_knight',
      ability: 'attacker',
      id: 0,
      firstTrainedDay: 0,
      SuitColors: 'black',
      StartingPower: 36,
      CurrentPower: 36,
      lastTimeTrained: undefined,
      HerosTrainingTimes: 0,
    },
    {
      name: 'flash',
      ability: 'defender',
      id: 0,
      firstTrainedDay: 0,
      SuitColors: 'red and yellow',
      StartingPower: 28,
      CurrentPower: 28,
      lastTimeTrained: undefined,
      HerosTrainingTimes: 0,
    },
    {
      name: 'super_man',
      ability: 'defender',
      id: 0,
      firstTrainedDay: 0,
      SuitColors: 'blue and red',
      StartingPower: 59,
      CurrentPower: 59,
      lastTimeTrained: undefined,
      HerosTrainingTimes: 0,
    },
    {
      name: 'joker',
      ability: 'attacker',
      id: 0,
      firstTrainedDay: 0,
      SuitColors: 'purple',
      StartingPower: 500,
      CurrentPower: 500,
      lastTimeTrained: undefined,
      HerosTrainingTimes: 0,
    },
    {
      name: 'wanda',
      ability: 'attacker',
      id: 0,
      firstTrainedDay: 0,
      SuitColors: 'red',
      StartingPower: 5858,
      CurrentPower: 5858,
      lastTimeTrained: undefined,
      HerosTrainingTimes: 0,
    },
    {
      name: 'black_widow',
      ability: 'defender',
      id: 0,
      firstTrainedDay: 0,
      SuitColors: 'black',
      StartingPower: 855,
      CurrentPower: 855,
      lastTimeTrained: undefined,
      HerosTrainingTimes: 0,
    },
    {
      name: 'ant_man',
      ability: 'attacker',
      id: 0,
      firstTrainedDay: 0,
      SuitColors: 'black and red',
      StartingPower: 858,
      CurrentPower: 858,
      lastTimeTrained: undefined,
      HerosTrainingTimes: 0,
    },
    {
      name: 'doctor_strange',
      ability: 'defender',
      id: 0,
      firstTrainedDay: 0,
      SuitColors: 'blue and red',
      StartingPower: 58,
      CurrentPower: 58,
      lastTimeTrained: undefined,
      HerosTrainingTimes: 0,
    },
    {
      name: 'spiderman_improved',
      ability: 'defender',
      id: 0,
      firstTrainedDay: 0,
      SuitColors: 'yellow and red',
      StartingPower: 252,
      CurrentPower: 252,
      lastTimeTrained: undefined,
      HerosTrainingTimes: 0,
    },
    {
      name: 'thor',
      ability: 'attacker',
      id: 0,
      firstTrainedDay: 0,
      SuitColors: 'red and gold',
      StartingPower: 100,
      CurrentPower: 100,
      lastTimeTrained: undefined,
      HerosTrainingTimes: 0,
    },
  ];
}
